name: Create Preview

on:
  pull_request_target:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - "posts/**"

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run composite action
        id: composite_action
        uses: ./.github/actions/workflow
        with:
          files: "posts/**"
          preview: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          MATRIX_ACCESS_TOKEN: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          SLACK_ACCESS_TOKEN: ${{ secrets.SLACK_ACCESS_TOKEN }}
          MASTODON_EU_FR_TOKEN: ${{ secrets.MASTODON_EU_FR_TOKEN }}
