name: Create Preview

on:
  pull_request_target:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - "posts/**"

jobs:
  setup:
    uses: ./.github/workflows/setup-secrets.yml

  preview:
    needs: setup
    name: Preview
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run composite action
        uses: ./.github/actions/galaxy-social
        with:
          preview: "true"
          PR_NUMBER: ${{ github.event.number }}
