name: Publish Content

on:
  pull_request_target:
    branches: [main]
    types: [closed]
    paths:
      - "posts/**"

jobs:
  setup:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/setup-secrets.yml

  publish:
    if: github.event.pull_request.merged == true
    needs: setup
    name: Publish content
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run composite action
        uses: ./.github/actions/galaxy-social
        with:
          PR_NUMBER: ${{ github.event.number }}